spring:
  flyway:
    enabled: false
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: api-seed-consumer-group-test
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topics:
      product-events: product-events-test

elasticsearch:
  host: localhost
  port: 9200
  scheme: http
  username: elastic
  password: changeme
  index:
    products: products-test

external:
  api:
    product:
      base-url: https://fakestoreapi.com
      timeout: 5000
      retry-attempts: 3
